### ISSUE TITLE
Tracking issue for improving test coverage of the action

### ISSUE THREAD

**Issue by danielsn** [model-checking/kani-github-action#5]
Currently, we only test a single small cago-kani example.  Possible improvements
 - [ ] Example that needs workspace
 - [ ] Example that needs --tests
 - [ ] example that has dependencies
 - [ ] example where the rust version matters
 - [ ] examples with different kani versions

**Comment by YoshikiTakashima** [comment]
I would also add
- [ ] expected fail tests
